POST http://localhost:5002/api/mailMasive
Content-Type: application/json

{
    "recipients": "encoexpresbuenaventura@gmail.com",
    "subject": "Envio de Prueba 2",
    "text": "envio correo de prueba 2"    
}
