name: Deploy to EC2

on:
  push:
    branches:
      - main # Cambia a tu rama principal si es diferente

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Deploy to EC2
      env:
        HOST: ${{ secrets.EC2_HOST }}
        USER: ${{ secrets.EC2_USER }}
        PEM_KEY: ${{ secrets.EC2_PEM_KEY }}
        DB_PORT: ${{ secrets.DB_PORT }}  
        DB_HOST: ${{ secrets.EC2_HOST }}  
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }} 
        DB_NAME: ${{ secrets.DB_NAME }}  
        PORT: ${{ secrets.PORT }}  
        EMAIL_USER: ${{ secrets.EMAIL_USER }}  
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}  
        JWT_EXPIRE_IN: ${{ secrets.JWT_EXPIRE_IN }}  
        JSON_SECRETO: ${{ secrets.JSON_SECRETO }}  
        PORT_REDIS: ${{ secrets.PORT_REDIS }}  
        HOST_REDIS: ${{ secrets.HOST_REDIS }}  
        DB_REDIS: ${{ secrets.DB_REDIS }}  
        PASSWORD_REDIS: ${{ secrets.PASSWORD_REDIS }}  
        REPO_URL: https://github.com/farkot09/backend-node-ecommerce-tt
        PROJECT_DIR: /home/ubuntu/backend-node-ecommerce-tt
      run: |
        echo "$PEM_KEY" | tr -d '\r' > deploy_key.pem
        chmod 600 deploy_key.pem
        ssh -i deploy_key.pem -o StrictHostKeyChecking=no $USER@$HOST << EOF
          if [ ! -d "$PROJECT_DIR" ]; then
            mkdir -p $PROJECT_DIR
            git clone $REPO_URL $PROJECT_DIR
          fi
          cd $PROJECT_DIR
          git reset --hard
          git pull origin main
          npm install

          echo "DB_PORT=$DB_PORT" >> .env
          echo "DB_HOST=$DB_HOST" >> .env
          echo "DB_PASSWORD=$DB_PASSWORD" >> .env
          echo "DB_NAME=$DB_NAME" >> .env
          echo "PORT=$PORT" >> .env
          echo "EMAIL_USER=$EMAIL_USER" >> .env
          echo "EMAIL_PASSWORD=$EMAIL_PASSWORD" >> .env
          echo "JWT_EXPIRE_IN=$JWT_EXPIRE_IN" >> .env
          echo "PORT_REDIS=$PORT_REDIS" >> .env
          echo "HOST_REDIS=$HOST_REDIS" >> .env
          echo "DB_REDIS=$DB_REDIS" >> .env
          echo "PASSWORD_REDIS=$PASSWORD_REDIS" >> .env
          echo "JSON_SECRETO=$JSON_SECRETO" >> .env

          sudo pm2 restart all || npm run start
        EOF
        rm deploy_key.pem
