name: Deploy to EC2

on:
  push:
    branches:
      - main # Cambia a tu rama principal si es diferente

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Deploy to EC2
      env:
        HOST: ${{ secrets.EC2_HOST }}
        USER: ${{ secrets.EC2_USER }}
        PEM_KEY: ${{ secrets.EC2_PEM_KEY }}
        REPO_URL: https://github.com/farkot09/backend-node-ecommerce-tt
        PROJECT_DIR: /home/ubuntu/backend-node-ecommerce-tt
      run: |
        echo "$PEM_KEY" | tr -d '\r' > deploy_key.pem
        chmod 600 deploy_key.pem
        ssh -i deploy_key.pem -o StrictHostKeyChecking=no $USER@$HOST << EOF
          if [ ! -d "$PROJECT_DIR" ]; then
            mkdir -p $PROJECT_DIR
            git clone $REPO_URL $PROJECT_DIR
          fi
          cd $PROJECT_DIR
          git reset --hard
          git pull origin main
          npm install
          sudo pm2 restart all || npm run start
        EOF
        rm deploy_key.pem
