POST http://localhost:5002/api/mailMasiveBatch
Content-Type: application/json

{
    "recipients": ["encoexpresbuenaventura@gmail.com", "viagramo2011@gmail.com"],
    "subject": "Envio de Prueba 3",
    "text": "envio correo de prueba 3"    
}
